# -*- coding: utf-8 -*-
"""Copia de ParcialIA2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9mqsj_htzLTaPtfYz_P0bia4b_aXFyd
"""

import tensorflow as tf
print(f"TensorFlow versión: {tf.__version__}")
print(f"GPU disponible: {tf.config.list_physical_devices('GPU')}")

# Verificación más explícita
if tf.config.list_physical_devices('GPU'):
    print("GPU activada correctamente")
else:
    print("GPU NO activada. Ve a Runtime → Change runtime type → T4 GPU")

"""Importamos Librerias


"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

# NLTK para preprocesamiento de texto
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Keras / TensorFlow para el modelo
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM, GRU, Bidirectional, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

# Scikit-learn para split y métricas
from sklearn.model_selection import train_test_split

# Para reproducibilidad
np.random.seed(42)
tf.random.set_seed(42)

# Descargar recursos NLTK (solo la primera vez)
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

print("Todas las librerías importadas correctamente")

""" CARGA DEL DATASET"""

RUTA_CSV = '/content/drive/MyDrive/Copia de IMDB Dataset.csv'

df = pd.read_csv(RUTA_CSV)
print(f"Dataset cargado: {df.shape[0]} filas, {df.shape[1]} columnas")
df.head()

print("\n--- MUESTRA DEL DATASET ---")
# Visualizar los ruidos del dataset
print(df[['review', 'sentiment']].head(20))
# cantidad de datos que tiene el dataset
total_inicial = len(df)
print(f"1. Datos totales al iniciar: {total_inicial}")

"""Visualizar datos repetidos

"""

duplicados = df.duplicated().sum()
print(f"2. Reseñas duplicadas encontradas: {duplicados}")

"""Eliminamos datos repetidos y visualizar el balance"""

#eliminamos datos repetidos
df = df.drop_duplicates(keep='first')
total_post_limpieza = len(df)
print(f"3. Datos reales tras eliminar duplicados: {total_post_limpieza}")

# Verificamos nuevo balance
print("\nBalance actual tras eliminar duplicados:")
print(df['sentiment'].value_counts())

"""Creamos un balance da los datos"""

# Identificamos la cantidad minima
min_cantidad = df['sentiment'].value_counts().min()

# Creamos un nuevo dataframe equilibrado tomando una muestra aleatoria de cada clase
df_equilibrado = df.groupby('sentiment').apply(lambda x: x.sample(n=min_cantidad, random_state=42)).reset_index(drop=True)

print("\n4. ¡Dataset Re-equilibrado con éxito!")
print(f"Nuevo total de datos: {len(df_equilibrado)}")
print("Distribución final:")
print(df_equilibrado['sentiment'].value_counts())

"""Limpieza al dataset


"""

def limpieza_dataset(text):
    # 1. Quitar HTML y URLs
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'http\S+', '', text)

    # 2. Normalización (Minúsculas y Contracciones)
    text = text.lower()
    text = re.sub(r"can't", "cannot", text)
    text = re.sub(r"n't", " not", text)
    text = re.sub(r"i'm", "i am", text)

    # 3. Limpieza de caracteres (Solo letras y espacios)
    text = re.sub(r'[^a-z\s]', '', text)

    # 4. Stopwords (Sin eliminar negaciones para proteger el sentimiento)
    stop_words = set(stopwords.words('english'))
    negaciones = {'not', 'no', 'never', 'neither', 'nor'}
    stop_words = stop_words - negaciones

    # 5. Lemmatización (Reducir a la raíz)
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(w) for w in text.split() if w not in stop_words]

    return " ".join(tokens)

"""Nuevo data set, limpio y listo"""

print("\n[PROCESO] Aplicando limpieza ")
df['review_clean'] = df['review'].apply(limpieza_dataset)

print("\n--- COMPARATIVA DE UN CASO REAL ---")
print(f"ORIGINAL:\n{df['review'].iloc[0][:150]}...")
print(f"\nLIMPIA (Para la IA):\n{df['review_clean'].iloc[0][:150]}...")

# Mostrar el dataset final que se usará para el modelo
print("\n--- DATASET LISTO PARA ENTRENAR ---")
print(df[['review_clean', 'sentiment']].head(20))

"""Guardar el data set limpio"""

df.to_csv('IMDB_Dataset_Limpio.csv', index=False)

"""Graficamos los datos limpios (Nuevos del dataset)"""

# mirar cuantos resultados positive y negative
import seaborn as sns
import matplotlib.pyplot as plt

# Crear el gráfico
plt.figure(figsize=(8, 5))
sns.countplot(x='sentiment', data=df, palette='viridis')

# Añadir títulos y etiquetas
plt.title('Distribución de Sentimientos en el Dataset')
plt.xlabel('Sentimiento')
plt.ylabel('Número de Reseñas')

# Mostrar el gráfico
plt.show()

"""TOKERIZACION DE LOS DATOS Y VECTORIZACION"""

# Configuraciones para la Red Neuronal
MAX_WORDS = 10000          # Tamaño del vocabulario
MAX_LEN = 200              # Todas las reseñas medirán 200 palabras
OOV_TOKEN = "<OOV>"        # Para palabras desconocidas

# Asegurar que df_equilibrado tenga la columna 'review_clean'
# Esto es crucial porque df_equilibrado fue creado antes de que 'review_clean' se añadiera a df
# y no heredó la columna 'review_clean'.
df_equilibrado['review_clean'] = df_equilibrado['review'].apply(limpieza_dataset)

tokenizer = Tokenizer(num_words=MAX_WORDS, oov_token=OOV_TOKEN)
tokenizer.fit_on_texts(df_equilibrado['review_clean'])

# Convertimos texto a secuencias de números
sequences = tokenizer.texts_to_sequences(df_equilibrado['review_clean'])

# Aplicamos Padding (relleno con ceros) para estandarizar el tamaño
X = pad_sequences(sequences, maxlen=MAX_LEN, padding='post', truncating='post')

# Convertimos sentimientos a números (Label Encoding)
# positive -> 1, negative -> 0
y = df_equilibrado['sentiment'].map({'positive': 1, 'negative': 0}).values

print("\n--- PROCESO COMPLETADO ---")
print(f"Diccionario de palabras creado: {len(tokenizer.word_index)} palabras.")
print(f"Matriz de entrada (X) lista: {X.shape}")
print(f"Vector de etiquetas (y) listo: {y.shape}")

# Ejemplo de cómo lo ve la IA ahora
print("\nEjemplo de reseña tokenizada (Primeros 15 números):")
print(X[0][:15])

"""##Split train tes"""

from sklearn.model_selection import train_test_split

# 80% train + 20% temporal
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 20% temporal → 10% val + 10% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

print(f"Train: {X_train.shape} | balance: {np.bincount(y_train)}")
print(f"Val:   {X_val.shape}   | balance: {np.bincount(y_val)}")
print(f"Test:  {X_test.shape}  | balance: {np.bincount(y_test)}")

"""##Crear modelo Birnn"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Embedding, SimpleRNN, LSTM, GRU,
    Bidirectional, Dense, Dropout
)

def crear_modelo_birnn(tipo_rnn='SimpleRNN',
                      vocab_size=MAX_WORDS,
                      embedding_dim=128,
                      max_len=MAX_LEN,
                      units_1=64,
                      units_2=32,
                      dropout_rate=0.3):
    """
    Crea un modelo Bidirectional RNN flexible.
    tipo_rnn puede ser 'SimpleRNN', 'LSTM' o 'GRU'.
    """
    capas_rnn = {
        'SimpleRNN': SimpleRNN,
        'LSTM': LSTM,
        'GRU': GRU
    }
    CapaRNN = capas_rnn[tipo_rnn]

    model = Sequential([
        Embedding(input_dim=vocab_size,
                  output_dim=embedding_dim,
                  input_length=max_len,
                  mask_zero=True),
        Bidirectional(CapaRNN(units_1, return_sequences=True)),
        Dropout(dropout_rate),
        Bidirectional(CapaRNN(units_2)),
        Dropout(dropout_rate),
        Dense(32, activation='relu'),
        Dropout(dropout_rate),
        Dense(1, activation='sigmoid')
    ], name=f'BiRNN_{tipo_rnn}')

    return model

# Creamos el modelo con SimpleRNN (la BiRNN pura)
model = crear_modelo_birnn(tipo_rnn='SimpleRNN')
model.summary()

from tensorflow.keras.optimizers import Adam

model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)
print("Modelo compilado")

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

# El modelo se guarda en la misma carpeta del Drive donde está el CSV
RUTA_MODELO = '/content/drive/MyDrive/CLASE IA DATA SCIENCE/mejor_modelo_birnn.keras'

callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=3,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=2,
        min_lr=1e-6,
        verbose=1
    ),
    ModelCheckpoint(
        RUTA_MODELO,
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    )
]
print("✅ Callbacks configurados")
print(f"   El mejor modelo se guardará en: {RUTA_MODELO}")

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=15,
    batch_size=64,
    callbacks=callbacks,
    verbose=1
)
print("✅ Entrenamiento completado")

# evaluación del modelo con métricas de clasificación binaria
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Predicciones sobre el conjunto Test

# Probabilidades continuas [0, 1]
y_prob = model.predict(X_test, verbose=0).flatten()

# Umbral 0.5 → etiquetas binarias
y_pred = (y_prob >= 0.5).astype(int)

print("Predicciones generadas sobre el conjunto de TEST")
print(f"   Total muestras evaluadas: {len(y_test)}")

# Accuracy y reporte de clasificacion
acc = accuracy_score(y_test, y_pred)
print(f"  ACCURACY EN TEST: {acc:.4f}  ({acc*100:.2f}%)")

print("\n--- REPORTE DETALLADO DE CLASIFICACIÓN ---")
print(classification_report(
    y_test, y_pred,
    target_names=['Negativo (0)', 'Positivo (1)']
))

# matriz de confusion
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(7, 5))
sns.heatmap(
    cm, annot=True, fmt='d', cmap='Blues',
    xticklabels=['Pred: Negativo', 'Pred: Positivo'],
    yticklabels=['Real: Negativo', 'Real: Positivo'],
    linewidths=0.5, linecolor='gray'
)
plt.title('Matriz de Confusión — BiRNN (Test Set)', fontsize=14, fontweight='bold')
plt.ylabel('Etiqueta Real', fontsize=12)
plt.xlabel('Etiqueta Predicha', fontsize=12)

#Anotar las 4 metricas en el grafico
tn, fp, fn, tp = cm.ravel()
plt.figtext(
    0.5, -0.05,
    f"TP={tp}  TN={tn}  FP={fp}  FN={fn}  |  "
    f"Precisión={tp/(tp+fp):.3f}  Recall={tp/(tp+fn):.3f}",
    ha='center', fontsize=10, color='navy'
)
plt.tight_layout()
plt.savefig('matriz_confusion.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Matriz de confusión guardada como 'matriz_confusion.png'")

#Curva ROC y AUC
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, color='darkorange', lw=2,
         label=f'Curva ROC  (AUC = {roc_auc:.4f})')
plt.plot([0, 1], [0, 1], color='navy', lw=1.5,
         linestyle='--', label='Clasificador Aleatorio (AUC = 0.50)')

# Punto de corte óptimo (Youden Index: maximiza TPR - FPR)
idx_optimo = np.argmax(tpr - fpr)
umbral_optimo = thresholds[idx_optimo]
plt.scatter(fpr[idx_optimo], tpr[idx_optimo],
            marker='o', color='red', s=80, zorder=5,
            label=f'Umbral óptimo = {umbral_optimo:.3f}')

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.02])
plt.xlabel('Tasa de Falsos Positivos (FPR)', fontsize=12)
plt.ylabel('Tasa de Verdaderos Positivos (TPR / Recall)', fontsize=12)
plt.title('Curva ROC — BiRNN Análisis de Sentimiento', fontsize=14, fontweight='bold')
plt.legend(loc='lower right', fontsize=11)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig('curva_roc.png', dpi=150)
plt.show()
print(f"✅ Curva ROC guardada | AUC = {roc_auc:.4f}")

#Curva de aprendizaje (loss y accuracy por epoca)
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# — Loss
axes[0].plot(history.history['loss'],     label='Train Loss',  lw=2)
axes[0].plot(history.history['val_loss'], label='Val Loss',    lw=2, linestyle='--')
axes[0].set_title('Pérdida por Época',  fontsize=13, fontweight='bold')
axes[0].set_xlabel('Época'); axes[0].set_ylabel('Binary Crossentropy')
axes[0].legend(); axes[0].grid(alpha=0.3)

# — Accuracy
axes[1].plot(history.history['accuracy'],     label='Train Accuracy', lw=2)
axes[1].plot(history.history['val_accuracy'], label='Val Accuracy',   lw=2, linestyle='--')
axes[1].set_title('Exactitud por Época', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Época'); axes[1].set_ylabel('Accuracy')
axes[1].legend(); axes[1].grid(alpha=0.3)

plt.suptitle('Curvas de Aprendizaje — BiRNN', fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('curvas_aprendizaje.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Curvas de aprendizaje guardadas")

# resumen de metricas
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall    = recall_score(y_test, y_pred)
f1        = f1_score(y_test, y_pred)

print("\n" + "="*55)
print("       RESUMEN FINAL DE EVALUACIÓN — BiRNN")
print("="*55)
print(f"  Accuracy          : {acc:.4f}  ({acc*100:.2f}%)")
print(f"  Precision         : {precision:.4f}")
print(f"  Recall (Sensib.)  : {recall:.4f}")
print(f"  F1-Score          : {f1:.4f}")
print(f"  AUC-ROC           : {roc_auc:.4f}")
print(f"  Umbral óptimo ROC : {umbral_optimo:.4f}")
print("="*55)
print(f"\n  TP={tp}  TN={tn}  FP={fp}  FN={fn}")
print("\n✅ Evaluación completa finalizada")

